name: Version Release Docker Image
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build and publish Docker image
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            os: ubuntu-latest
            tag-prefix: -amd64
          - platform: linux/arm64
            os: ubuntu-24.04-arm
            tag-prefix: -arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_NAMESPACE }}/rallly
          tags: |
            type=semver,pattern={{version}}${{ matrix.tag-prefix }}
            type=semver,pattern={{major}}.{{minor}}${{ matrix.tag-prefix }}
            type=semver,pattern={{major}}${{ matrix.tag-prefix }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          file: ./apps/web/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            SELF_HOSTED=true
